package me.nov.dalvikgate.transform;

/**
 * Transform some type to another.
 *
 * @param <I> Input type to transform.
 * @param <T> Type generated by transformation process.
 */
public interface ITransformer<I, T> {

  /**
   * Call {@link #build(Object)} then {@link #buildDone()}.
   *
   * @param input Value to transform.
   */
  default void visit(I input) {
    build(input);
    buildDone();
  }

  /**
   * Build the transformed value from the input type.
   *
   * @param input Value to transform.
   */
  void build(I input);

  /**
   * Called after {@link #build(I)} completes.
   */
  default void buildDone() {
  }

  /**
   * Retrieve the value generated by {@link #build(I)}
   *
   * @return Stored value.
   */
  T getTransformed();
}
